export const USERS = [
  {
    name: "Hoang Nguyenfafadfadadadadadada",
    email: "hoang@gmail.com",
    role: "student",
    status: "active",
    createdAt: "Apr 4, 2025",
    lastLogin: "Apr 18, 2025",
  },
  {
    name: "Linh Tran",
    email: "linh.tran@example.com",
    role: "teacher",
    status: "inactive",
    createdAt: "Mar 28, 2025",
    lastLogin: "Apr 1, 2025",
  },
  {
    name: "Minh Pham",
    email: "minh.pham@example.com",
    role: "student",
    status: "active",
    createdAt: "Feb 10, 2025",
    lastLogin: "Mar 15, 2025",
  },
  {
    name: "Thu Le",
    email: "thu.le@example.com",
    role: "admin",
    status: "active",
    createdAt: "Jan 20, 2025",
    lastLogin: "Apr 15, 2025",
  },
  {
    name: "An Vo",
    email: "an.vo@example.com",
    role: "student",
    status: "inactive",
    createdAt: "Mar 2, 2025",
    lastLogin: "Mar 25, 2025",
  },
  {
    name: "Khoa Dang",
    email: "khoa.dang@example.com",
    role: "teacher",
    status: "active",
    createdAt: "Feb 5, 2025",
    lastLogin: "Apr 17, 2025",
  },
  {
    name: "Chi Bui",
    email: "chi.bui@example.com",
    role: "student",
    status: "active",
    createdAt: "Apr 1, 2025",
    lastLogin: "Apr 18, 2025",
  },
  {
    name: "Hien Nguyen",
    email: "hien.nguyen@example.com",
    role: "teacher",
    status: "inactive",
    createdAt: "Jan 15, 2025",
    lastLogin: "Feb 20, 2025",
  },
  {
    name: "Quang Le",
    email: "quang.le@example.com",
    role: "admin",
    status: "active",
    createdAt: "Dec 10, 2024",
    lastLogin: "Apr 10, 2025",
  },
  {
    name: "Trang Do",
    email: "trang.do@example.com",
    role: "student",
    status: "active",
    createdAt: "Mar 30, 2025",
    lastLogin: "Apr 12, 2025",
  },
  {
    name: "Nam Phan",
    email: "nam.phan@example.com",
    role: "student",
    status: "inactive",
    createdAt: "Feb 8, 2025",
    lastLogin: "Feb 22, 2025",
  },
  {
    name: "Tuan Vo",
    email: "tuan.vo@example.com",
    role: "teacher",
    status: "active",
    createdAt: "Mar 6, 2025",
    lastLogin: "Apr 18, 2025",
  },
  {
    name: "Lan Huynh",
    email: "lan.huynh@example.com",
    role: "parent",
    status: "active",
    createdAt: "Apr 3, 2025",
    lastLogin: "Apr 18, 2025",
  },
  {
    name: "Dat Nguyen",
    email: "dat.nguyen@example.com",
    role: "student",
    status: "active",
    createdAt: "Apr 2, 2025",
    lastLogin: "Apr 16, 2025",
  },
  {
    name: "Tam Le",
    email: "tam.le@example.com",
    role: "admin",
    status: "inactive",
    createdAt: "Jan 5, 2025",
    lastLogin: "Mar 25, 2025",
  },
  {
    name: "Vy Tran",
    email: "vy.tran@example.com",
    role: "student",
    status: "active",
    createdAt: "Mar 25, 2025",
    lastLogin: "Apr 15, 2025",
  },
  {
    name: "Nhat Dang",
    email: "nhat.dang@example.com",
    role: "parent",
    status: "active",
    createdAt: "Feb 15, 2025",
    lastLogin: "Mar 30, 2025",
  },
  {
    name: "Bao Chau",
    email: "bao.chau@example.com",
    role: "teacher",
    status: "active",
    createdAt: "Mar 10, 2025",
    lastLogin: "Apr 17, 2025",
  },
  {
    name: "Son Pham",
    email: "son.pham@example.com",
    role: "student",
    status: "inactive",
    createdAt: "Feb 25, 2025",
    lastLogin: "Mar 20, 2025",
  },
  {
    name: "Ha Nguyen",
    email: "ha.nguyen@example.com",
    role: "parent",
    status: "active",
    createdAt: "Apr 5, 2025",
    lastLogin: "Apr 18, 2025",
  }
];
